// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file proto/v1/kv.proto (package proto.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetRequest, GetResponse, PutRequest, PutResponse } from "./kv_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service proto.v1.KvService
 */
export const KvService = {
  typeName: "proto.v1.KvService",
  methods: {
    /**
     * @generated from rpc proto.v1.KvService.Get
     */
    get: {
      name: "Get",
      I: GetRequest,
      O: GetResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.v1.KvService.Put
     */
    put: {
      name: "Put",
      I: PutRequest,
      O: PutResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

